src/Intrix/BackendBundle/Entity/Produto.php
<?php

namespace Intrix\BackendBundle\Entity;

use Symfony\Bridge\Doctrine\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * Produto
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Intrix\BackendBundle\Entity\ProdutoRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Assert\UniqueEntity(fields="nome", message="Esse produto já foi cadastrado.", groups={"registro"})
 * @Assert\UniqueEntity(fields="codigo", message="Ouve um erro ao cadastrar o código do produto.", groups={"registro"})
 */
class Produto {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=false, unique=true)
     */
    private $nome;

    /**
     * @var string
     *
     * @ORM\Column(type="string", columnDefinition="ENUM('1', '2', '3')", options={"comment" = "1 = Em estoque, 2 = Em falta, 3 = Inativo"}, nullable=false)
     * 
     */
    private $status;

    /**
     * @var float $preco
     *
     * @ORM\Column(type="float", nullable=false)
     * 
     */
    private $preco;

    /**
     *
     * @var text
     * @ORM\Column(type="text", nullable=true)
     * 
     */
    private $descricao;

    /**
     * @ORM\ManyToOne(targetEntity="Categoria", inversedBy="produtos")
     * @ORM\JoinColumn(name="categoria_id", referencedColumnName="id", nullable=false)
     */
    private $categoria;

    /**
     * @ORM\OneToMany(targetEntity="Venda", mappedBy="produto")
     */
    private $vendas;

    /**
     *
     * @var text
     * @ORM\Column(type="string", nullable=false, unique=true)
     *  
     */
    private $codigo;

    /**
     * Constructor
     */
    public function __construct() {
        $this->vendas = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nome
     *
     * @param string $nome
     * @return Produto
     */
    public function setNome($nome) {
        $this->nome = $nome;

        return $this;
    }

    /**
     * Get nome
     *
     * @return string 
     */
    public function getNome() {
        return $this->nome;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return Produto
     */
    public function setStatus($status) {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string 
     */
    public function getStatus() {
        return $this->status;
    }

    /**
     * Set preco
     *
     * @param float $preco
     * @return Produto
     */
    public function setPreco($preco) {
        $this->preco = $preco;

        return $this;
    }

    /**
     * Get preco
     *
     * @return float 
     */
    public function getPreco() {
        return $this->preco;
    }

    /**
     * Set descricao
     *
     * @param string $descricao
     * @return Produto
     */
    public function setDescricao($descricao) {
        $this->descricao = $descricao;

        return $this;
    }

    /**
     * Get descricao
     *
     * @return string 
     */
    public function getDescricao() {
        return $this->descricao;
    }

    /**
     * Set categoria
     *
     * @param \Intrix\BackendBundle\Entity\Categoria $categoria
     * @return Produto
     */
    public function setCategoria(\Intrix\BackendBundle\Entity\Categoria $categoria = null) {
        $this->categoria = $categoria;

        return $this;
    }

    /**
     * Get categoria
     *
     * @return \Intrix\BackendBundle\Entity\Categoria 
     */
    public function getCategoria() {
        return $this->categoria;
    }

    /**
     * Add vendas
     *
     * @param \Intrix\BackendBundle\Entity\Venda $vendas
     * @return Produto
     */
    public function addVenda(\Intrix\BackendBundle\Entity\Venda $vendas) {
        $this->vendas[] = $vendas;

        return $this;
    }

    /**
     * Remove vendas
     *
     * @param \Intrix\BackendBundle\Entity\Venda $vendas
     */
    public function removeVenda(\Intrix\BackendBundle\Entity\Venda $vendas) {
        $this->vendas->removeElement($vendas);
    }

    /**
     * Get vendas
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getVendas() {
        return $this->vendas;
    }

    /**
     * Set codigo
     *
     * @param string $codigo
     * @return Produto
     */
    public function setCodigo($codigo) {
        $this->codigo = $codigo;

        return $this;
    }

    /**
     * Get codigo
     *
     * @return string 
     */
    public function getCodigo() {
        return $this->codigo;
    }

    public function getStatusFormated() {
        switch ($this->status) {
            case '1':
                return 'Em estoque';
            case '2':
                return 'Em falta';
            case '3':
                return 'Inativo';
            default :
                return $this->status;
        }
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist($em) {
        if (is_null($this->getId())) {
            $categoria = str_pad($this->getCategoria()->getId(), 3, "0", STR_PAD_LEFT);
            $produtos = $em->getEntityManager()->getRepository("BackendBundle:Produto")->findByCategoria($this->getCategoria()->getId());

            $produto = str_pad((count($produtos) + 1), 4, "0", STR_PAD_LEFT);
            $this->codigo = $categoria . "." . $produto;
        }
    }

}

src/Intrix/BackendBundle/Form/ProdutoType.php
<?php

namespace Intrix\BackendBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Intrix\BackendBundle\Entity\CategoriaRepository;

class ProdutoType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {

        $builder
                ->add('categoria', 'entity', array(
                    'empty_value' => 'Selecione...',
                    'class' => 'BackendBundle:Categoria',
                    'property' => 'nome',
                    'query_builder' => function(CategoriaRepository $er) {
                        return $er->getAllAtivos();
                    },
                    'attr' => array(
                        'placeholder' => 'Escolha uma categoria...',
                        'class' => 'select',
                        'tabindex' => '2'
                    ),
                    'label' => 'Categoria',
                ))
                ->add('nome', 'text', array(
                    'attr' => array('class' => 'form-control'),
                    'label' => 'Produto',
                ))
                ->add('preco', 'money', array(
                    'attr' => array('class' => 'form-control preco'),
                    'label' => 'Valor',
                    'currency' => 'BRL',
                    'grouping' => true
                ))
                ->add('status', 'choice', array(
                    'attr' => array(
                        'data-placeholder' => 'Escolha...',
                        'class' => 'select',
                        'tabindex' => '2'
                    ),
                    'label' => 'Status',
                    'choices' => array(
                        '0' => 'Escolha...',
                        '1' => 'Em estoque',
                        '2' => 'Em falta',
                        '3' => 'Inativo',
                    )
                ))
                ->add('descricao', 'textarea', array(
                    'label' => 'Observação',
                    'attr' => array(
                        'rows' => '5',
                        'cols' => '5',
                        'class' => 'form-control'
                    )
                ))
                ->add('codigo', 'hidden');
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'Intrix\BackendBundle\Entity\Produto',
            'attr' => array(
                'class' => 'form-horizontal',
                'role' => 'form',
                'titulo' => 'Produto'
            ),
            'validation_groups' => array('registro')
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'intrix_backendbundle_produto';
    }

}

src/Intrix/BackendBundle/Controller/ProdutoController.php
<?php

namespace Intrix\BackendBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Intrix\BackendBundle\Entity\Produto;
use Intrix\BackendBundle\Form\ProdutoType;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * Produto controller.
 *
 */
class ProdutoController extends Controller {

    /**
     * Lists all Produto entities.
     *
     */
    public function indexAction() {
        $em = $this->getDoctrine()->getManager();

        $produtos = $em->getRepository('BackendBundle:Produto')->findAll();

        return $this->render('BackendBundle:Produto:index.html.twig', array(
                    'entities' => $produtos,
        ));
    }

    /**
     * Displays a form to create a new Produto entity.
     *
     */
    public function newAction() {
        $entity = new Produto();
        $form = $this->createCreateForm($entity);

        return $this->render('BackendBundle:Produto:new.html.twig', array(
                    'entity' => $entity,
                    'form' => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Produto entity.
     *
     * @param Produto $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Produto $entity) {
        $form = $this->createForm(new ProdutoType(), $entity, array(
            'action' => $this->generateUrl('produto_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Creates a new Produto entity.
     *
     */
    public function createAction(Request $request) {
        $entity = new Produto();
        $form = $this->createCreateForm($entity);
        $request = $this->savePreco($request);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            $request->getSession()->getFlashBag()->add(
                    'notice', 'Produto salvo com sucesso!'
            );
            return $this->redirect($this->generateUrl('produto_new'));
        }

        return $this->render('BackendBundle:Produto:new.html.twig', array(
                    'entity' => $entity,
                    'form' => $form->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Produto entity.
     *
     */
    public function editAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BackendBundle:Produto')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Não foi possivel encontrar esse produto.');
        }

        $editForm = $this->createEditForm($entity);

        return $this->render('BackendBundle:Produto:edit.html.twig', array(
                    'entity' => $entity,
                    'edit_form' => $editForm->createView(),
        ));
    }

    /**
     * Creates a form to edit a Produto entity.
     *
     * @param Produto $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Produto $entity) {
        $form = $this->createForm(new ProdutoType(), $entity, array(
            'action' => $this->generateUrl('produto_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }

    /**
     * Edits an existing Produto entity.
     *
     */
    public function updateAction(Request $request, $id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BackendBundle:Produto')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Não foi possivel encontrar esse produto.');
        }

        $editForm = $this->createEditForm($entity);
        $request = $this->savePreco($request);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            $request->getSession()->getFlashBag()->add(
                    'notice', 'Produto salvo com sucesso!'
            );
            return $this->redirect($this->generateUrl('produto_edit', array('id' => $id)));
        }

        return $this->render('BackendBundle:Produto:edit.html.twig', array(
                    'entity' => $entity,
                    'edit_form' => $editForm->createView(),
        ));
    }

    public function ajaxPrecoAction($id) {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('BackendBundle:Produto')->findOneById($id);
        
        return new JsonResponse(array('preco' => $entity->getPreco()));
    }

    private function savePreco($request) {
        $aSave = array('', '.');
        $aMask = array('.', ',');
        $aPost = $request->request->all();
        $aPost['intrix_backendbundle_produto']['preco'] = str_replace($aMask, $aSave, $aPost['intrix_backendbundle_produto']['preco']);
        $request->request->replace($aPost);

        return $request;
    }

}

src/Intrix/BackendBundle/Resources/views/Produto/edit.html.twig
{% extends 'BackendBundle:Layout:layout.html.twig' %}

{% block body %}
    <div class="page-title">
        <h5><i class="fa fa-file-o"></i> Editando o produto: {{ edit_form.vars.value.nome }}</h5>
    </div>
    <!-- Statistics -->
    <ul class="row stats">
        <li class="col-xs-3"><a href="#" class="btn btn-default">52,00</a> <span>Saldo Inicial</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-success">520,00</a> <span>Dinheiro em caixa</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-danger">14,00</a> <span>Dinheiro Retirado</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-info">48,00</a> <span>Gasto com serviço</span></li>
    </ul>
    <!-- /statistics -->
    <!-- Right labels -->
    {{ form(edit_form) }}

{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{{ asset('backend/js/produto/produto.js') }}"></script>
{% endblock %}

src/Intrix/BackendBundle/Resources/views/Produto/index.html.twig
{% extends 'BackendBundle:Layout:layout.html.twig' %}

{% block body %}

    <!-- Page title -->
    <div class="page-title">
        <h5><i class="fa fa-file-o"></i> Lista de produtos</h5>
        <div class="btn-group">
            <a href="#" class="btn btn-link btn-lg btn-icon dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cogs"></i><span class="caret"></span></a>
            <ul class="dropdown-menu dropdown-menu-right">
                <li><a href="{{ path('produto_new') }}">Adicionar um produto</a></li>
            </ul>
        </div>
    </div>
    <!-- Statistics -->
    <ul class="row stats">
        <li class="col-xs-3"><a href="#" class="btn btn-default">52,00</a> <span>Saldo Inicial</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-success">520,00</a> <span>Dinheiro em caixa</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-danger">14,00</a> <span>Dinheiro Retirado</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-default">48,00</a> <span>Gasto com serviço</span></li>
    </ul>
    <!-- /statistics -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h6 class="panel-title">Produtos</h6>
        </div>
        <div class="datatable">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>Preço</th>
                        <th>Status</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entity in entities %}
                        <tr class="success">
                            <td>{{ entity.codigo }}</td>
                            <td>{{ entity.nome }}</td>
                            <td>R$ {{ entity.preco|number_format(2, ',', '.') }}</td>
                            <td>{{ entity.statusFormated }}</td>
                            <td>
                                <div class="table-controls">
                                    <a title="" class="btn btn-default btn-icon btn-xs tip" href="{{ path('produto_edit', { 'id': entity.id }) }}" data-original-title="Editar"><i class="fa fa-pencil"></i></a>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

src/Intrix/BackendBundle/Resources/views/Produto/new.html.twig
{% extends 'BackendBundle:Layout:layout.html.twig' %}

{% block body %}
    <div class="page-title">
        <h5><i class="fa fa-file-o"></i> Cria um novo produto</h5>
    </div>
    <!-- Statistics -->
    <ul class="row stats">
        <li class="col-xs-3"><a href="#" class="btn btn-default">52,00</a> <span>Saldo Inicial</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-success">520,00</a> <span>Dinheiro em caixa</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-danger">14,00</a> <span>Dinheiro Retirado</span></li>
        <li class="col-xs-3"><a href="#" class="btn btn-info">48,00</a> <span>Gasto com serviço</span></li>
    </ul>
    <!-- /statistics -->
    <!-- Right labels -->
    {{ form(form) }}

{% endblock %}
{% block javascript %}
    <script type="text/javascript" src="{{ asset('backend/js/produto/produto.js') }}"></script>
{% endblock %}